-- Create the leads table
create table public.leads (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text,
  email text not null,
  phone text not null,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  status text default 'New' -- New, Contacted, Closed
);

-- Enable Row Level Security (RLS)
alter table public.leads enable row level security;

-- Policy for INSERT (Public can insert)
create policy "Allow public to insert leads"
  on public.leads
  for insert
  to anon, authenticated
  with check (true);

-- Policy for SELECT (Only authenticated/admin can view)
create policy "Allow authenticated users to view leads"
  on public.leads
  for select
  to authenticated
  using (true);

-- Policy for UPDATE (Only authenticated/admin can update status)
create policy "Allow authenticated users to update leads"
  on public.leads
  for update
  to authenticated
  using (true);

-- Policy for DELETE (Only authenticated/admin can delete)
create policy "Allow authenticated users to delete leads"
  on public.leads
  for delete
  to authenticated
  using (true);
