-- Create the properties table
create table public.properties (
  id bigint generated by default as identity primary key,
  title text not null,
  location text not null,
  price text not null,
  size text not null,
  type text not null,
  images text[] not null,
  description text not null,
  highlights text[] not null,
  features text[] not null,
  map_link text,
  site_plan text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.properties enable row level security;

-- Create policy to allow public read access
create policy "Allow public read access"
  on public.properties
  for select
  to public
  using (true);

-- Insert initial data
insert into public.properties (title, location, price, size, type, images, description, highlights, features, site_plan)
values
  (
    'Emerald Greens Phase I',
    'Parandur, Chennai',
    '12.5 Lakhs',
    '1200 Sq.ft',
    'Residential Plot',
    ARRAY['https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1200&auto=format&fit=crop', 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=400&auto=format&fit=crop', 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=400&auto=format&fit=crop'],
    'Emerald Greens Phase I offers premium residential plots in the rapidly developing region of Parandur, right next to the upcoming Chennai Greenfield Airport. This project is designed for those looking for high appreciation potential and a secure investment. The layout is fully approved by DTCP and features wide blacktop roads, street lights, and abundant groundwater.',
    ARRAY['Next to New Parandur Airport', '10 Minute Drive from Bangalore Highway', 'Sweet Ground Water at 20ft', 'Surrounded by Residential Houses'],
    ARRAY['DTCP Approved', 'Corner Plot', 'Park View', 'Blacktop Roads', 'Street Lights'],
    'https://images.unsplash.com/photo-1599827592476-c48c90961858?q=80&w=1200&auto=format&fit=crop'
  ),
  (
    'Royal Enclave',
    'Sriperumbudur, Chennai',
    '18.5 Lakhs',
    '1500 Sq.ft',
    'Residential Plot',
    ARRAY['https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?q=80&w=1200&auto=format&fit=crop', 'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?q=80&w=400&auto=format&fit=crop'],
    'Royal Enclave is a premium gated community located in the industrial hub of Sriperumbudur. Ideal for immediate construction, the community is already home to over 50 families. With excellent connectivity to the Chennai-Bangalore highway and proximity to major industrial parks, this is a perfect choice for both end-users and investors.',
    ARRAY['Gated Community with 24/7 Security', '5 Mins from SIPCOT Industrial Park', 'Ready for Construction'],
    ARRAY['Gated Community', 'Blacktop Roads', 'Ready to Build', 'Club House Access'],
    'https://images.unsplash.com/photo-1599827592476-c48c90961858?q=80&w=1200&auto=format&fit=crop'
  ),
  (
    'Harvest Hills Managed Farmland',
    'Arakkonam, Chennai',
    '25 Lakhs',
    '10000 Sq.ft',
    'Farmland',
    ARRAY['https://images.unsplash.com/photo-1500076656116-558758c991c1?q=80&w=1200&auto=format&fit=crop', 'https://images.unsplash.com/photo-1500076656116-558758c991c1?q=80&w=400&auto=format&fit=crop'],
    'Experience the joy of farming without the hassle. Harvest Hills offers professionally managed farmland where you own the land, and we manage the cultivation. Enjoy weekend getaways in your own farm, complete with a clubhouse, swimming pool, and guest cottages. We grow high-value timber and organic fruits to ensure regular returns.',
    ARRAY['Free Resort Membership', 'Tax-Free Agriculture Income', 'Weekend Retreat Spot'],
    ARRAY['Managed Farm', 'Free Membership', 'Organic Yield', 'Guest Cottages'],
    'https://images.unsplash.com/photo-1599827592476-c48c90961858?q=80&w=1200&auto=format&fit=crop'
  ),
  (
    'Lakeview Gardens',
    'Oragadam, Chennai',
    '15 Lakhs',
    '1200 Sq.ft',
    'Residential Plot',
    ARRAY['https://images.unsplash.com/photo-1560518883-ce09059ee971?q=80&w=1200&auto=format&fit=crop'],
    'Situated in the automobile capital of South India, Lakeview Gardens offers scenic plots overlooking a serene lake. The location boasts rapid infrastructure development and high interpolation potential. It is an excellent choice for long-term wealth creation.',
    ARRAY['Scenic Lake View', 'High Appreciation Potential', 'Clear Titles'],
    ARRAY['Lake Facing', 'Investment Choice', 'High Growth Area'],
    'https://images.unsplash.com/photo-1599827592476-c48c90961858?q=80&w=1200&auto=format&fit=crop'
  ),
  (
    'Golden Orchard',
    'Kanchipuram',
    '45 Lakhs',
    '22000 Sq.ft',
    'Farmland',
    ARRAY['https://images.unsplash.com/photo-1629814696096-74fc215c267c?q=80&w=1200&auto=format&fit=crop'],
    'Golden Orchard offers expansive half-acre farm plots with rich red soil, perfect for cultivation. Each plot comes with its own borewell and fencing. Located just outside the temple city of Kanchipuram, it offers a peaceful retreat with spiritual connectivity.',
    ARRAY['Individual Borewell', 'Rich Red Soil', 'Fencing Included'],
    ARRAY['Red Soil', 'Borewell', 'Fencing Done'],
    'https://images.unsplash.com/photo-1599827592476-c48c90961858?q=80&w=1200&auto=format&fit=crop'
  ),
  (
    'City Avenue Extension',
    'Tambaram West',
    '32 Lakhs',
    '1000 Sq.ft',
    'Residential Plot',
    ARRAY['https://images.unsplash.com/photo-1592595896551-12b371d546d5?q=80&w=1200&auto=format&fit=crop'],
    'City Avenue Extension brings you premium city plots within the CMDA limits of Tambaram. Enjoy the convenience of city living with metro access, top schools, and hospitals just minutes away. A rare opportunity to own a plot within the city grid.',
    ARRAY['CMDA Approved', 'Metro Connectivity', 'City Limits'],
    ARRAY['CMDA Approved', 'Metro Access', 'Premium Location'],
    'https://images.unsplash.com/photo-1599827592476-c48c90961858?q=80&w=1200&auto=format&fit=crop'
  );
